### ISSUE TITLE
[Feature] Add support for mTLS

### ISSUE THREAD

**Issue by pims** [mehrdadrad/gping#1]
Nice project!

To safely expose the server part, it would be great to add support for mTLS.
It would help with reducing potential abuse, and help with enforcing rate-limits.

gRPC has already [good support for this](https://github.com/grpc/grpc-go/issues/403). Lots of examples as well: https://itnext.io/practical-guide-to-securing-grpc-connections-with-go-and-tls-part-1-f63058e9d6d1.

Thoughts?

**Comment by mehrdadrad** [comment]
@pims thanks for suggesting this feature. i added it but later i need to create a doc
